export type Color = `#${string}`

export type ColorPalette = Record<number, Color>

export type HightideColors = {
  white: Color,
  black: Color,
  transparent: Color,
  gray: ColorPalette,
  green: ColorPalette,
  orange: ColorPalette,
  purple: ColorPalette,
  blue: ColorPalette,
  red: ColorPalette,
}

export type HightideSemanticColors = {
  transparent: Color,
  background: Color,
  onBackground: Color,
  warning: Color,
  onWarning: Color,
  warningHover: Color,
  positive: Color,
  onPositive: Color,
  positiveHover: Color,
  negative: Color,
  onNegative: Color,
  negativeHover: Color,
  disabled: Color,
  onDisabled: Color,
  surface: Color,
  onSurface: Color,
  surfaceHover: Color,
  surfaceVariant: Color,
  onSurfaceVariant: Color,
  surfaceWarning: Color,
  onSurfaceWarning: Color,
  textPrimary: Color,
  textSecondary: Color,
  textTertiary: Color,
  placeholder: Color,
  description: Color,
  label: Color,
  primary: Color,
  onPrimary: Color,
  primaryHover: Color,
  secondary: Color,
  onSecondary: Color,
  secondaryHover: Color,
  neutral: Color,
  onNeutral: Color,
  neutralHover: Color,
  neutralText: Color,
  neutralTextHover: Color,
  neutralOutline: Color,
  neutralOutlineHover: Color,
  neutralTonalText: Color,
  neutralTonalBackground: Color,
  faded: Color,
  highlight: Color,
  border: Color,
  divider: Color,
}
