import type { ColorToken } from '../primitive/color'

export type ThemeRoleColorTokens = {
  primary: ColorToken,
  onPrimary: ColorToken,
  primaryHover: ColorToken,
  secondary: ColorToken,
  onSecondary: ColorToken,
  secondaryHover: ColorToken,
  positive: ColorToken,
  onPositive: ColorToken,
  positiveHover: ColorToken,
  warning: ColorToken,
  onWarning: ColorToken,
  warningHover: ColorToken,
  negative: ColorToken,
  onNegative: ColorToken,
  negativeHover: ColorToken,
  neutral: ColorToken,
  onNeutral: ColorToken,
  neutralHover: ColorToken,
  neutralText: ColorToken,
  neutralTextHover: ColorToken,
  neutralOutline: ColorToken,
  neutralOutlineHover: ColorToken,
  neutralTonalText: ColorToken,
  neutralTonalBackground: ColorToken,
}

export type HightideSemanticColorTokens = {
  transparent: ColorToken,
  background: ColorToken,
  onBackground: ColorToken,
  disabled: ColorToken,
  onDisabled: ColorToken,
  surface: ColorToken,
  onSurface: ColorToken,
  surfaceHover: ColorToken,
  surfaceVariant: ColorToken,
  placeholder: ColorToken,
  description: ColorToken,
  faded: ColorToken,
  menuBorder: ColorToken,
  progressTrack: ColorToken,
  switchThumbInactive: ColorToken,
  switchThumbActive: ColorToken,
  switchBorder: ColorToken,
  border: ColorToken,
  divider: ColorToken,
}

export const hightideSemanticColorKeys = [
  'transparent',
  'background',
  'onBackground',
  'disabled',
  'onDisabled',
  'surface',
  'onSurface',
  'surfaceHover',
  'surfaceVariant',
  'placeholder',
  'description',
  'faded',
  'menuBorder',
  'progressTrack',
  'switchThumbInactive',
  'switchThumbActive',
  'switchBorder',
  'border',
  'divider',
] as const satisfies readonly (keyof HightideSemanticColorTokens)[]
