import type { ColorToken } from '../primitive/color'

export type HightideSemanticColorTokens = {
  background: ColorToken,
  onBackground: ColorToken,
  warning: ColorToken,
  onWarning: ColorToken,
  warningHover: ColorToken,
  positive: ColorToken,
  onPositive: ColorToken,
  positiveHover: ColorToken,
  negative: ColorToken,
  onNegative: ColorToken,
  negativeHover: ColorToken,
  disabled: ColorToken,
  onDisabled: ColorToken,
  surface: ColorToken,
  onSurface: ColorToken,
  surfaceHover: ColorToken,
  surfaceVariant: ColorToken,
  onSurfaceVariant: ColorToken,
  surfaceWarning: ColorToken,
  onSurfaceWarning: ColorToken,
  textPrimary: ColorToken,
  textSecondary: ColorToken,
  textTertiary: ColorToken,
  placeholder: ColorToken,
  description: ColorToken,
  label: ColorToken,
  primary: ColorToken,
  onPrimary: ColorToken,
  primaryHover: ColorToken,
  secondary: ColorToken,
  onSecondary: ColorToken,
  secondaryHover: ColorToken,
  neutral: ColorToken,
  onNeutral: ColorToken,
  neutralHover: ColorToken,
  neutralText: ColorToken,
  neutralTextHover: ColorToken,
  neutralOutline: ColorToken,
  neutralOutlineHover: ColorToken,
  neutralTonalText: ColorToken,
  neutralTonalBackground: ColorToken,
  faded: ColorToken,
  highlight: ColorToken,
}
