export type {
  InputContainerStyle as TextareaContainerStyle,
  InputIconStyle as TextareaIconStyle,
  InputPlaceholderStyle as TextareaPlaceholderStyle,
  InputState as TextareaState,
  InputStateLayerStyle as TextareaStateLayerStyle,
  InputTextStyle as TextareaTextStyle,
  InputThemeResolvers as TextareaThemeResolvers
} from './input'
