import { basicColorPalette } from './color-basic'
import type { HexColor, ThemeColorTokens, ThemeMode } from './types'

export type SemanticColorTokenMap = {
  background: HexColor,
  onBackground: HexColor,
  warning: HexColor,
  onWarning: HexColor,
  warningHover: HexColor,
  positive: HexColor,
  onPositive: HexColor,
  positiveHover: HexColor,
  negative: HexColor,
  onNegative: HexColor,
  negativeHover: HexColor,
  disabled: HexColor,
  onDisabled: HexColor,
  surface: HexColor,
  onSurface: HexColor,
  surfaceHover: HexColor,
  surfaceVariant: HexColor,
  onSurfaceVariant: HexColor,
  surfaceWarning: HexColor,
  onSurfaceWarning: HexColor,
  textPrimary: HexColor,
  textSecondary: HexColor,
  textTertiary: HexColor,
  placeholder: HexColor,
  description: HexColor,
  label: HexColor,
  primary: HexColor,
  onPrimary: HexColor,
  primaryHover: HexColor,
  secondary: HexColor,
  onSecondary: HexColor,
  secondaryHover: HexColor,
  neutral: HexColor,
  onNeutral: HexColor,
  neutralHover: HexColor,
  neutralText: HexColor,
  neutralTextHover: HexColor,
  neutralOutline: HexColor,
  neutralOutlineHover: HexColor,
  neutralTonalText: HexColor,
  neutralTonalBackground: HexColor,
  faded: HexColor,
  highlight: HexColor,
}

const { gray, green, orange, red, purple, blue, white, black } = basicColorPalette

const semanticColorsLight = {
  background: gray[75],
  onBackground: gray[900],
  warning: orange[500],
  onWarning: white,
  warningHover: orange[600],
  positive: green[500],
  onPositive: white,
  positiveHover: green[600],
  negative: red[500],
  onNegative: white,
  negativeHover: red[600],
  disabled: gray[300],
  onDisabled: gray[500],
  surface: gray[25],
  onSurface: gray[900],
  surfaceHover: white,
  surfaceVariant: white,
  onSurfaceVariant: gray[900],
  surfaceWarning: orange[100],
  onSurfaceWarning: orange[500],
  textPrimary: gray[900],
  textSecondary: gray[600],
  textTertiary: gray[300],
  placeholder: gray[500],
  description: gray[600],
  label: gray[700],
  primary: purple[500],
  onPrimary: white,
  primaryHover: purple[600],
  secondary: blue[500],
  onSecondary: white,
  secondaryHover: blue[600],
  neutral: gray[150],
  onNeutral: black,
  neutralHover: gray[200],
  neutralText: black,
  neutralTextHover: gray[500],
  neutralOutline: black,
  neutralOutlineHover: gray[600],
  neutralTonalText: black,
  neutralTonalBackground: gray[300],
  faded: gray[250],
  highlight: blue[500],
} as const satisfies SemanticColorTokenMap

const semanticColorsDark = {
  background: gray[850],
  onBackground: gray[100],
  warning: orange[500],
  onWarning: white,
  warningHover: orange[600],
  positive: green[700],
  onPositive: white,
  positiveHover: green[600],
  negative: red[500],
  onNegative: white,
  negativeHover: red[600],
  disabled: gray[500],
  onDisabled: gray[300],
  surface: gray[800],
  onSurface: gray[100],
  surfaceHover: gray[700],
  surfaceVariant: gray[900],
  onSurfaceVariant: gray[100],
  surfaceWarning: orange[900],
  onSurfaceWarning: orange[500],
  textPrimary: gray[100],
  textSecondary: gray[400],
  textTertiary: gray[600],
  placeholder: gray[500],
  description: gray[400],
  label: gray[300],
  primary: purple[400],
  onPrimary: white,
  primaryHover: purple[500],
  secondary: blue[500],
  onSecondary: white,
  secondaryHover: blue[600],
  neutral: gray[750],
  onNeutral: white,
  neutralHover: gray[600],
  neutralText: white,
  neutralTextHover: gray[500],
  neutralOutline: gray[200],
  neutralOutlineHover: gray[400],
  neutralTonalText: white,
  neutralTonalBackground: gray[400],
  faded: gray[650],
  highlight: blue[500],
} as const satisfies SemanticColorTokenMap

export const semanticColors: ThemeColorTokens<SemanticColorTokenMap> = {
  light: semanticColorsLight,
  dark: semanticColorsDark,
}

export const getSemanticColors = (mode: ThemeMode): SemanticColorTokenMap => semanticColors[mode]
