import { basicColorPalette } from './color-basic'
import { semanticColors } from './color-semantic'
import type { HexColor, ThemeColorTokens, ThemeMode } from './types'

export type ComponentColorTokenMap = {
  carouselDotActive: HexColor,
  carouselDotDisabled: HexColor,
  inputBackground: HexColor,
  inputText: HexColor,
  menuBackground: HexColor,
  menuText: HexColor,
  menuBorder: HexColor,
  overlayBackground: HexColor,
  overlayText: HexColor,
  overlayShadow: HexColor,
  progressIndicatorFill: HexColor,
  progressIndicatorBackground: HexColor,
  processModelEdgeStroke: HexColor,
  processModelEdgeLabelBg: HexColor,
  processModelEdgeLabelTextStrong: HexColor,
  processModelEdgeLabelTextMuted: HexColor,
  processModelTerminalFill: HexColor,
  processModelTerminalFillActive: HexColor,
  processModelTerminalFillVisited: HexColor,
  processModelActivityIconBg: HexColor,
  processModelNodeActiveRing: HexColor,
  processModelNodeActiveBg: HexColor,
  processModelNodeVisitedBorder: HexColor,
  processModelNodeVisitedBg: HexColor,
  propertyTitleBackground: HexColor,
  propertyTitleText: HexColor,
  scrollbarTrack: HexColor,
  scrollbarThumb: HexColor,
  stepperBarDotActive: HexColor,
  stepperBarDotNormal: HexColor,
  stepperBarDotDisabled: HexColor,
  switchThumbInactive: HexColor,
  switchThumbActive: HexColor,
  tableBackground: HexColor,
  tableText: HexColor,
  tableHeaderBackground: HexColor,
  tableRowHoverBackground: HexColor,
  textImagePrimaryBackground: HexColor,
  textImagePrimaryText: HexColor,
  textImageSecondaryBackground: HexColor,
  textImageSecondaryText: HexColor,
  textImageDarkBackground: HexColor,
  textImageDarkText: HexColor,
  tooltipBackground: HexColor,
  tooltipText: HexColor,
  border: HexColor,
  divider: HexColor,
  focus: HexColor,
  outline: HexColor,
  outlineVariant: HexColor,
}

const { gray, purple, blue, white } = basicColorPalette
const light = semanticColors.light
const dark = semanticColors.dark

const componentColorsLight = {
  carouselDotActive: light.primary,
  carouselDotDisabled: light.disabled,
  inputBackground: light.surfaceVariant,
  inputText: light.onSurface,
  menuBackground: light.surfaceVariant,
  menuText: light.onSurface,
  menuBorder: gray[200],
  overlayBackground: light.surface,
  overlayText: light.onSurface,
  overlayShadow: '#00000039',
  progressIndicatorFill: light.primary,
  progressIndicatorBackground: gray[300],
  processModelEdgeStroke: light.primary,
  processModelEdgeLabelBg: gray[100],
  processModelEdgeLabelTextStrong: light.primary,
  processModelEdgeLabelTextMuted: purple[300],
  processModelTerminalFill: light.primary,
  processModelTerminalFillActive: light.primaryHover,
  processModelTerminalFillVisited: purple[400],
  processModelActivityIconBg: purple[100],
  processModelNodeActiveRing: purple[100],
  processModelNodeActiveBg: purple[50],
  processModelNodeVisitedBorder: purple[200],
  processModelNodeVisitedBg: '#fdf9ff',
  propertyTitleBackground: gray[100],
  propertyTitleText: light.description,
  scrollbarTrack: '#00000033',
  scrollbarThumb: gray[600],
  stepperBarDotActive: light.primary,
  stepperBarDotNormal: purple[100],
  stepperBarDotDisabled: light.description,
  switchThumbInactive: light.onSurface,
  switchThumbActive: white,
  tableBackground: light.surface,
  tableText: light.onSurface,
  tableHeaderBackground: light.surfaceVariant,
  tableRowHoverBackground: light.surfaceHover,
  textImagePrimaryBackground: light.primary,
  textImagePrimaryText: white,
  textImageSecondaryBackground: blue[500],
  textImageSecondaryText: white,
  textImageDarkBackground: blue[900],
  textImageDarkText: white,
  tooltipBackground: light.surfaceVariant,
  tooltipText: light.description,
  border: gray[200],
  divider: gray[100],
  focus: light.primary,
  outline: gray[100],
  outlineVariant: gray[200],
} as const satisfies ComponentColorTokenMap

const componentColorsDark = {
  carouselDotActive: dark.primary,
  carouselDotDisabled: dark.disabled,
  inputBackground: dark.surfaceVariant,
  inputText: dark.onSurface,
  menuBackground: dark.surfaceVariant,
  menuText: dark.onSurface,
  menuBorder: gray[600],
  overlayBackground: dark.surface,
  overlayText: dark.onSurface,
  overlayShadow: '#00000060',
  progressIndicatorFill: dark.primary,
  progressIndicatorBackground: gray[700],
  processModelEdgeStroke: dark.primary,
  processModelEdgeLabelBg: gray[700],
  processModelEdgeLabelTextStrong: dark.primary,
  processModelEdgeLabelTextMuted: purple[300],
  processModelTerminalFill: dark.primary,
  processModelTerminalFillActive: dark.primaryHover,
  processModelTerminalFillVisited: purple[400],
  processModelActivityIconBg: purple[100],
  processModelNodeActiveRing: purple[100],
  processModelNodeActiveBg: gray[700],
  processModelNodeVisitedBorder: purple[200],
  processModelNodeVisitedBg: gray[750],
  propertyTitleBackground: gray[750],
  propertyTitleText: dark.description,
  scrollbarTrack: '#ffffff33',
  scrollbarThumb: gray[300],
  stepperBarDotActive: dark.primary,
  stepperBarDotNormal: purple[100],
  stepperBarDotDisabled: dark.description,
  switchThumbInactive: dark.onSurface,
  switchThumbActive: dark.onSurface,
  tableBackground: dark.surface,
  tableText: dark.onSurface,
  tableHeaderBackground: dark.surfaceVariant,
  tableRowHoverBackground: dark.surfaceHover,
  textImagePrimaryBackground: dark.primary,
  textImagePrimaryText: white,
  textImageSecondaryBackground: blue[500],
  textImageSecondaryText: white,
  textImageDarkBackground: blue[900],
  textImageDarkText: white,
  tooltipBackground: dark.surfaceVariant,
  tooltipText: dark.description,
  border: gray[600],
  divider: gray[700],
  focus: dark.primary,
  outline: gray[700],
  outlineVariant: gray[600],
} as const satisfies ComponentColorTokenMap

export const componentColors: ThemeColorTokens<ComponentColorTokenMap> = {
  light: componentColorsLight,
  dark: componentColorsDark,
}

export const getComponentColors = (mode: ThemeMode): ComponentColorTokenMap => componentColors[mode]
