name: Test hightide-native

on:
  push:
    branches:
      - main
    paths:
      - "packages/hightide-native/**"
      - "packages/hightide-utils/**"
      - "packages/hightide-design/**"
      - ".github/workflows/test-hightide-native.yaml"
  pull_request:
    branches:
      - "**"
    paths:
      - "packages/hightide-native/**"
      - "packages/hightide-utils/**"
      - "packages/hightide-design/**"
      - ".github/workflows/test-hightide-native.yaml"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          version: 11.13.0

      - uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: pnpm

      - run: pnpm install --frozen-lockfile
      - run: pnpm --filter @helpwave/hightide-utils run init
      - run: pnpm --filter @helpwave/hightide-design run init
      - run: pnpm --filter @helpwave/hightide-native run init
      - run: pnpm --filter @helpwave/hightide-native run build
      - run: pnpm --filter @helpwave/hightide-native test
